### ISSUE TITLE
NoSuchMethodError: Attempted to use type 'ThreesApp' as a function

### ISSUE THREAD

**Issue by arden** [diov/threes-flutter#3]
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
NoSuchMethodError: Attempted to use type 'ThreesApp' as a function. Since types do not define a method 'call', this is not possible. Did you intend to call the ThreesApp constructor and forget the 'new' operator?
Receiver: ThreesApp
Tried calling: ThreesApp()
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      main (/Users/weibo/data/source/flutter/threes-flutter/lib/main.dart:9:32)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:279)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

**Comment by diov** [comment]
因为用了 Dart 2 的语法，需要配置。
可以参考官方给的WIKI [Trying the preview of Dart 2 in Flutter](https://github.com/flutter/flutter/wiki/Trying-the-preview-of-Dart-2-in-Flutter)
